
ami: "{{ ami |default('ami-efd0428f') }}"
region: "{{ region | default('us-west-2') }}"
ansible_ssh_private_key_file: '~/.ssh/kuba_oregon.1705.pem' #key to log into
#ssh_key: '~/.ssh/kuba_aws_west2.pem' #Your ssh key that is used to create the instance
location: frankfurt

role: mgmt

env_name: 'spot'

#allow change VPC (routing)
allow_vpc_change: True

# VPC
spot_vpc: 
    vpc:
        name: spot
        cidr_block: 10.218.0.0/22
        subnets:
          - cidr: 10.218.0.0/24
            resource_tags:
                Name: spot_pub
    route:
      - subnets:
          - 10.218.0.0/24
        routes:
          - dest: 0.0.0.0/0
            gw: igw
        resource_tags:
          Name:  spot default route

    security_groups:
        name: spot-security-group
        description: spot SG
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 89.70.92.47/32
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 87.206.148.14/32
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 89.70.92.163/32
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 89.70.90.8/32
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 212.67.156.30/32   #homeA
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 10.218.0.0/24 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 35.177.228.4/32 #mgmt 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ current_ip | default('1.2.3.4/32') }}"
          - proto: icmp
            from_port: -1
            to_port: -1
            cidr_ip: 0.0.0.0/0
    ec2_eip:
        instance_A:
          tag: 1A
          ip: 1.2.3.4
          name: 'stg-spot-test103'
    instance_group: spot1
