---
- name: install packages
  apt: name={{ item }}
  with_items:
    - opencl-headers
    - libcurl4-gnutls-dev
    - nvidia-libopencl1-375
    - ubuntu-drivers-common

- name: relink
  shell: ln -snf /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so

- name: mkdir sia
  file: 
    path: "~/{{ item }}"
    state: directory
  with_items:
      - siad
      - siaui
      - siaminer

- name: get sia-gpu-miner
  get_url:
      url: "{{ item.url }}"
      dest: "{{ item.path }}"
  with_items:
      - { url: "https://github.com/NebulousLabs/Sia-GPU-Miner/releases/download/v1.1.0/sia-gpu-miner-v1.1.0-linux64.zip", path: "~/siaminer" }
      - { url: "https://github.com/NebulousLabs/Sia/releases/download/v1.2.1/Sia-v1.2.1-linux-amd64.zip", path: "~/siad" }
      - { url: "https://github.com/NebulousLabs/Sia-UI/releases/download/v1.2.1/Sia-UI-v1.2.1-linux-x64.zip", path: "~/siaui" }

- name: install repository
  apt_repository: repo={{ item }} validate_certs={{ validate_certs |default(True) }}
  with_items:
    - ppa:graphics-drivers/ppa

- name: install packages
  apt: name={{ item }}
  with_items:
    - nvidia-cuda-toolkit
    - libxss1

- name: install siaminer
  shell: "cd ~/siaminer; unzip sia-gpu-miner-v1.1.0-linux64.zip"
- name: install siad
  shell: "cd ~/siad; unzip Sia-v1.2.1-linux-amd64.zip"
- name: install siaui
  shell: "cd ~/siaui; unzip Sia-UI-v1.2.1-linux-x64.zip"

- name: startsiad
  shell: "screen -S siad -d -m sh -c 'cd ~/siad/Sia-v1.2.1-linux-amd64; ./siad -M cghmrtw; exec bash'"

#- name: startsiac
#  shell: "screen -S siac -d -m sh -c 'cd ~/siad/Sia-v1.2.1-linux-amd64; ./siac wallet init; exec bash'"
#- name: startsiac unlock wallet
#  shell: "screen -S siac -d -m sh -c 'cd ~/siad/Sia-v1.2.1-linux-amd64; ./siac wallet unlock; exec bash'"

#curl -i -A "Sia-Agent" -X POST localhost:9980/wallet/unlock?encryptionpassword=

- name: startsiad
  shell: "screen -S siaminer -d -m sh -c 'cd ~/siaminer; ./sia-gpu-miner; exec bash'"

