---
- debug: var=hostvars[item]
  with_items: "{{ play_hosts }}"

- name: Debug apache vhosts configuration.
  template:
    src: "vhosts.conf"
    dest: "~/vhosts.conf"
    owner: root
    group: root
    mode: 0644
  #notify: restart apache
